### ISSUE TITLE
Hostapd install issues

### ISSUE THREAD

**Issue by rickbase1** [lostincynicism/hostapd-rtl8188#1]
Hi, thanks for creating this updated version of Hostapd.  I am a bit of a noob and can not seem to get it to run properly.  Here are the steps I took to try to get it to run on my RPi2.  I am thinking maybe I missed a step.  Would you please look through my work and let me know where I went wrong.

My apoligies if this is the incorrect form for this.

Thanks,

Rick

_First I started with the usual_

sudo apt-get update
sudo apt-get upgrade

_then added needed libraries_

sudo apt-get install  libnl-genl-3-dev libcurl4-openssl-dev (these were needed to complete the build)

_I then edited the defconfig file in /hostapd-rtl8188/hostapd and uncommented the following_

CONFIG_IEEE80211N=y
CONFIG_IEEE80211AC=y
CONFIG_LIBNL32=y

_Then I compiled it :_

./config (didn't do anything)
sudo make  ( no errors after installing needed libraries)
sudo make install

_Then I created a new directory and created a new hostapd file:_

mkdir /etc/hostapd
sudo nano /etc/hostapd/hostapd.conf

_and installed a basic configuration_
- When I try to launch the app it will not run with the command*

sudo service hostapd start
hostapd: unrecognized service

_when I do a version check I get:_

pi@Symmetry-RPI ~/hostapd-rtl8188/hostapd $ hostapd -v
hostapd v2.4 for Realtek rtl871xdrv
User space daemon for IEEE 802.11 AP management,
IEEE 802.1X/WPA/WPA2/EAP/RADIUS Authenticator
Copyright (c) 2002-2015, Jouni Malinen j@w1.fi and contributors

_if I try to run it from the command line I get this:_

pi@Symmetry-RPI ~/hostapd-rtl8188/hostapd $ hostapd -d /etc/hostapd/hostapd.conf
random: Trying to read entropy from /dev/random
Configuration file: /etc/hostapd/hostapd.conf
Line 3: unknown configuration item '    interface'
Line 5: unknown configuration item '    bridge'
Line 7: unknown configuration item '    driver'
Line 9: unknown configuration item '    country_code'
Line 11: unknown configuration item '    ctrl_interface'
Line 13: unknown configuration item '    ctrl_interface_group'
Line 15: unknown configuration item '    ssid'
Line 17: unknown configuration item '    hw_mode'
Line 19: unknown configuration item '    channel'
Line 21: unknown configuration item '    wpa'
Line 23: unknown configuration item '    wpa_passphrase'
Line 25: unknown configuration item '    wpa_key_mgmt'
Line 27: unknown configuration item '    wpa_pairwise'
Line 29: unknown configuration item '    rsn_pairwise'
Line 31: unknown configuration item '    beacon_int'
Line 33: unknown configuration item '    auth_algs'
Line 35: unknown configuration item '    macaddr_acl'
Line 37: unknown configuration item '    wmm_enabled'
Line 39: unknown configuration item '    eap_reauth_period'
19 errors found in configuration file '/etc/hostapd/hostapd.conf'
Failed to set up interface with /etc/hostapd/hostapd.conf
hostapd_init: free iface 0xd796d0
Failed to initialize interface
- and then I run out of ideas*

**Comment by rickbase1** [comment]
After more research I see that I should have copied defconfig to .config as that is where the Makefile looks.  After doing that now when I run "sudo make" I have lots more errors to contend with.

I tried installing freeradius but that did not help

I tried commented out all EAP references in the defconfig file but that did not help either.  It seems I am missing some critical EAP library but not sure which one. 

Any ideas?

Thanks

Rick

**Comment by rickbase1** [comment]
This is my make error log for reference
pi@Symmetry-RPI ~/hostapd-rtl8188/hostapd $ make
main.o: In function `hostapd_global_deinit':
/home/pi/hostapd-rtl8188/hostapd/main.c:371: undefined reference to`tncs_global_deinit'
main.o: In function `hostapd_global_run':
/home/pi/hostapd-rtl8188/hostapd/main.c:404: undefined reference to`tncs_global_init'
../src/ap/hostapd.o: In function `hostapd_setup_bss':
/home/pi/hostapd-rtl8188/hostapd/../src/ap/hostapd.c:874: undefined reference to`tncs_global_init'
../src/ap/authsrv.o: In function `hostapd_sim_db_cb':
/home/pi/hostapd-rtl8188/hostapd/../src/ap/authsrv.c:43: undefined reference to`radius_server_eap_pending_cb'
../src/ap/authsrv.o: In function `authsrv_deinit':
/home/pi/hostapd-rtl8188/hostapd/../src/ap/authsrv.c:209: undefined reference to`radius_server_deinit'
/home/pi/hostapd-rtl8188/hostapd/../src/ap/authsrv.c:222: undefined reference to `eap_sim_db_deinit'
../src/ap/authsrv.o: In function`authsrv_init':
/home/pi/hostapd-rtl8188/hostapd/../src/ap/authsrv.c:185: undefined reference to `eap_sim_db_init'
../src/ap/authsrv.o: In function`hostapd_setup_radius_srv':
/home/pi/hostapd-rtl8188/hostapd/../src/ap/authsrv.c:130: undefined reference to `radius_server_init'
../src/drivers/drivers.o:(.data+0x8): undefined reference to`wpa_driver_wired_ops'
../src/drivers/drivers.o:(.data+0xc): undefined reference to `wpa_driver_rtw_ops'
ctrl_iface.o: In function`hostapd_ctrl_iface_receive':
/home/pi/hostapd-rtl8188/hostapd/ctrl_iface.c:2092: undefined reference to `radius_server_erp_flush'
ctrl_iface.o: In function`hostapd_ctrl_iface_mib':
/home/pi/hostapd-rtl8188/hostapd/ctrl_iface.c:1785: undefined reference to `radius_server_get_mib'
../src/eap_server/eap_server_peap.o: In function`eap_peap_process_phase2_soh':
/home/pi/hostapd-rtl8188/hostapd/../src/eap_server/eap_server_peap.c:839: undefined reference to `tncs_process_soh'
../src/eap_server/eap_server_peap.o: In function`eap_peap_build_phase2_soh':
/home/pi/hostapd-rtl8188/hostapd/../src/eap_server/eap_server_peap.c:245: undefined reference to `tncs_build_soh_request'
eap_register.o: In function`eap_server_register_methods':
/home/pi/hostapd-rtl8188/hostapd/eap_register.c:81: undefined reference to `eap_server_sim_register'
/home/pi/hostapd-rtl8188/hostapd/eap_register.c:86: undefined reference to`eap_server_aka_register'
/home/pi/hostapd-rtl8188/hostapd/eap_register.c:91: undefined reference to `eap_server_aka_prime_register'
/home/pi/hostapd-rtl8188/hostapd/eap_register.c:96: undefined reference to`eap_server_pax_register'
/home/pi/hostapd-rtl8188/hostapd/eap_register.c:101: undefined reference to `eap_server_psk_register'
/home/pi/hostapd-rtl8188/hostapd/eap_register.c:106: undefined reference to`eap_server_sake_register'
/home/pi/hostapd-rtl8188/hostapd/eap_register.c:111: undefined reference to `eap_server_gpsk_register'
/home/pi/hostapd-rtl8188/hostapd/eap_register.c:121: undefined reference to`eap_server_fast_register'
/home/pi/hostapd-rtl8188/hostapd/eap_register.c:131: undefined reference to `eap_server_ikev2_register'
/home/pi/hostapd-rtl8188/hostapd/eap_register.c:136: undefined reference to`eap_server_tnc_register'
/home/pi/hostapd-rtl8188/hostapd/eap_register.c:141: undefined reference to `eap_server_pwd_register'
/home/pi/hostapd-rtl8188/hostapd/eap_register.c:146: undefined reference to`eap_server_eke_register'
collect2: ld returned 1 exit status
Makefile:954: recipe for target 'hostapd' failed
make: **\* [hostapd] Error 1

**Comment by PlantDaddy** [comment]
"sudo service hostapd start
hostapd: unrecognized service"

This project is only for compiling the hostapd binary with the RTL8188 chipset driver. It's not a package that includes the upstart scripts.

"CONFIG_IEEE80211N=y
CONFIG_IEEE80211AC=y"

AC is not going to work, as this chipset isn't an AC chipset.
Do you already have hostapd 2.4 installed elsewhere?
What distro are you running this on?

If you need AC, I can't help with that as the chipset doesn't support AC, and this project wouldn't work for those needs.

**Comment by rickbase1** [comment]
ok, thanks.  I ended up buying a new USB modem that Hostapd supported.
