### ISSUE TITLE
RTL8192CUS: ioctl[RTL_IOCTL_HOSTAPD]: Invalid argument

### ISSUE THREAD

**Issue by joe271828** [lostincynicism/hostapd-rtl8188#2]
Function of USB dongle with RTL8192CUS on Raspberry PI 2 is normal, but the Linux booting log show “ioctl[RTL_IOCTL_HOSTAPD]: Invalid argument”.
The linux kernel version is 3.18.20 and the driver version of rtl8192.so is v4.0.2_9000.20130911.

**Comment by PlantDaddy** [comment]
Yeah, I'm not sure about this. This is an error that comes from the upstream code, not the small portions I contributed. I haven't noticed an issue, so I'm not concerned about it.

**Comment by PlantDaddy** [comment]
Closing: Since this doesn't have a known impact, and to be honest, driver programming isn't my strong suit.
