### ISSUE TITLE
Make Hostapd RTL work with 80211AC

### ISSUE THREAD

**Issue by cannonfodder728** [lostincynicism/hostapd-rtl8188#4]
Some changes to make this hostapd rtl variant work with 80211AC

1) Uncomment "CONFIG_IEEE80211AC=y" in .config file
2) Comment "#CONFIG_LIBNL20=y" and "#CONFIG_LIBNL32=y" in .config file
3) edit src/ap/hw_features.c file to find "Failed to request a scan of neighboring BSSes ret=%d (%s)" and change "return -1" to "return 0"

**Comment by PlantDaddy** [comment]
So this fork just includes rtl8188cus drivers which is a wireless n card. It doesn't have ac capabilities. So I don't see how that would be any benefit.
